### ISSUE TITLE
Best way to contribute?

### ISSUE THREAD

**Issue by carpeliam** [Parrit/Parrit#111]
Hey Parrit friends! I followed the instructions in the `contibuting.md` to get added to the Slack but haven't heard anything in a while - I understand some folks have moved on and maybe not everybody's checking the associated gmail account. Is there a good way to pick up development? Pinging @Pinwheeler in the hopes that perhaps he knows The Secrets.

**Comment by carpeliam** [comment]
oh, and @liquidMocha too!

**Comment by liquidMocha** [comment]
Hello @carpeliam ! Thanks for reaching out! I can add you to our Slack channel. What email can I use to find you on Slack?

**Comment by carpeliam** [comment]
Thanks @liquidMocha! liam@carpeliam.com is best for me.

**Comment by liquidMocha** [comment]
Added carpeliam to Slack
