### ISSUE TITLE
Vertical dragging issues

### ISSUE THREAD

**Issue by pgoodwin** [Parrit/Parrit#15]
Sometimes I can't drag and drop "parrits" from a pairing board that is higher on the screen to one that is lower. Since the pairing boards can't be moved this makes it impossible to use the app. This seems to be more of an issue with smaller screens. It's a problem on my laptop, but I can't do anything at all on my phone. I have nine pairs on my team, which may be a contributing factor.

**Comment by jgreubel** [comment]
https://www.pivotaltracker.com/story/show/132039679

**Comment by jgreubel** [comment]
Hey Phil, sorry for the long delay.  I just got off a project and found some time to work on Parrit again and I believe I have fixed this issue.  We are confirming it ourselfs, but feel free to check it out on parrit-test.cfapps.io, login user:test pass:test.

**Comment by jgreubel** [comment]
This is fixed to our best knowledge.  Please re-open or make a new issue if you are still having problems.

**Comment by pgoodwin** [comment]
Cool!
