### ISSUE TITLE
http should redirect to https

### ISSUE THREAD

**Issue by mcwumbly** [Parrit/Parrit#41]
it seems that both http and https are supported.  would be good to make everyone use https so that login credentials are not accidentally submitted in the clear.

**Comment by moleske** [comment]
Just a note:
https://support.run.pivotal.io/entries/82035305-How-do-I-force-my-users-to-use-HTTPS-
http://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/reference/htmlsingle/#ns-requires-channel

**Comment by robdimsdale** [comment]
I'd like to +1 this on behalf of our team. Our team is more than happy to contribute the necessary changes if it's a matter of bandwidth.

**Comment by Pinwheeler** [comment]
@robdimsdale if you're able to do so that would be super awesome!

**Comment by robdimsdale** [comment]
We emailed `parrit@pivotal.io` to join slack as per the [contributing docs](https://github.com/Parrit/Parrit/blob/master/docs/Contributing.md) but I'm happy to keep the discussion here instead (it's easier).

@Pinwheeler any particular preferences as to how/where you would like to see this implemented?

**Comment by Pinwheeler** [comment]
we've migrated over to HTTPS thanks to the wonderful folks at Let'sEncrypt
