### ISSUE TITLE
User should receive confirmation response when clicking 'Record Pairs'

### ISSUE THREAD

**Issue by danjahner** [Parrit/Parrit#42]
Lack of response causes uncertainty of whether the pairs were recorded and/or rage clicking when a user is expecting a response.

**Comment by moleske** [comment]
note: related to existing issue #7 I believe

**Comment by jgreubel** [comment]
@moleske It kinda is, but this is just user feedback in general I believe, where as #7 is giving the ability to delete a previous pairing record.

**Comment by jgreubel** [comment]
This story may act as enough feedback when clicking Record Pairs: https://www.pivotaltracker.com/story/show/132040609

**Comment by jgreub** [comment]
Just released the above feature!
