### ISSUE TITLE
Shows last time paired in the pairing board

### ISSUE THREAD

**Issue by genevievelesperance** [Parrit/Parrit#44]
It'd be cool to see when the last time people were paired somewhere in the pairing board (ex: '4 days')

**Comment by jgreubel** [comment]
Is opening the History tab and looking at the last time pairing was saved good enough?

![image](https://cloud.githubusercontent.com/assets/14078561/25059448/d8de4ee6-213b-11e7-9f1f-2616d394da28.png)

**Comment by jgreubel** [comment]
This may also be solved with this tracker story: https://www.pivotaltracker.com/story/show/132040609

**Comment by jgreubel** [comment]
I am closing this issue since in order to keep issues up to date.  Feel free to re-open or make a new issue.
