### ISSUE TITLE
attempting to create a project with a name that already exists results in "unknown error"

### ISSUE THREAD

**Issue by mcwumbly** [Parrit/Parrit#47]
_As an_ anchor _I want_ to see an error message on the landing page _so that_ when I am creating a new project I am alerted of a name that is already in use by another team 

__Given__ I am creating a new project from the landing page 
__When__ I type a project name that exists
__Then__ I should see an error message that alerts me to try another project name

__Notes__: Please implement error message as per designs 
Error messages should read: _Not again. That name already exists, try a different one._

-------
In the logs, it show:

```
2016-12-05T19:42:59.47-0800 [APP/PROC/WEB/0]OUT   Detail: Key (name)=(foo) already exists.
```

**Comment by jgreubel** [comment]
DONE!
