### ISSUE TITLE
Recommend pairs takes a very long time with a big team

### ISSUE THREAD

**Issue by kittle31** [Parrit/Parrit#60]
we have 19 people in our "team"  when I click "reccomend pairs"  the application appears non responsive.
Checking the chrome deugger shows the request pending, and eventually I see a 504 timeout error after 5mins of waiting.

**Comment by jgreub** [comment]
Hey @kittle31.  Sorry for the long long delayed response.  But!  I just pushed a change to Parrit that should speed pair recommendations up for larger projects and for projects that have been around for a long time (multiple years).

https://github.com/Parrit/Parrit/releases/tag/v0.1.7

Re-open this if you still are seeing delays or timeouts.
