### ISSUE TITLE
History is taking a lot of time to load

### ISSUE THREAD

**Issue by sharibj** [Parrit/Parrit#74]
As a daily Parrit user, we have a lot of records in history although the team is small and pairs are repeated almost twice a week.
It would be good to have an option to clear all history before a certain timestamp to speed up the suggestion.

**Comment by liquidMocha** [comment]
Loading history should be faster now. @sharibj is it fast enough for your team?

**Comment by liquidMocha** [comment]
We've resolved the N+1 issue in the history query so this should be pretty fast even for teams with long histories.
